# Generated by Django 4.2 on 2023-09-29 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sportmen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=120)),
                ('titul', models.CharField(max_length=1200)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('time', models.CharField(max_length=1200, verbose_name='saat like 10:00 or 10:00-11:00')),
                ('sportfield', models.CharField(max_length=1200)),
                ('location', models.CharField(max_length=1200)),
                ('meeting_id', models.TextField(blank=True, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('meeting_duration', models.CharField(max_length=120, verbose_name='gorus vaxti')),
                ('meeter', models.ManyToManyField(related_name='meetings', to=settings.AUTH_USER_MODEL)),
                ('meetingowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adventures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Eager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=120)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_moderator', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
