# Generated by Django 4.2.5 on 2023-10-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportmen',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
