# Generated by Django 4.2.5 on 2023-10-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingapp', '0003_meeting_content_meeting_title_alter_sportmen_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='content2',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
    ]
