# Generated by Django 4.2.5 on 2023-10-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingapp', '0005_partners'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bigimage', models.ImageField(upload_to='')),
                ('smallimage', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=190, verbose_name='180-190 herf max content')),
                ('content2', models.CharField(max_length=120, verbose_name='110-120 herf max content')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('subject', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=120)),
                ('message', models.CharField(max_length=120)),
            ],
        ),
    ]
