# Generated by Django 4.2 on 2023-10-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingapp', '0006_about_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minititle1', models.CharField(max_length=120)),
                ('title1', models.CharField(max_length=200)),
                ('minititle2', models.CharField(max_length=120)),
                ('title2', models.CharField(max_length=200)),
                ('minititle3', models.CharField(max_length=120)),
                ('title3', models.CharField(max_length=200)),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
                ('image3', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='bigimage',
            field=models.ImageField(upload_to='', verbose_name='630-522'),
        ),
        migrations.AlterField(
            model_name='about',
            name='smallimage',
            field=models.ImageField(upload_to='', verbose_name='344-285'),
        ),
    ]
