# Generated by Django 4.2 on 2023-10-10 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetingapp', '0009_forgottenpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportmen',
            name='personal_information',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='forgottenpassword',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forgot', to=settings.AUTH_USER_MODEL),
        ),
    ]
