# Generated by Django 4.2.6 on 2023-10-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingapp', '0010_sportmen_personal_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eager',
            name='field',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
